services:

  redis_cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
      
  cliapp:
    build: 
      context: ./dockerfiles
      dockerfile: Dockerfile.cliapp
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis_cache
    depends_on: 
      - redis_cache
        #condition: service_healthy
    
  webapp:
    build: 
      context: ./dockerfiles
      dockerfile: Dockerfile.webapp
    ports:
    - 80:80
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis_cache
    depends_on: 
      - redis_cache 
        #condition: service_healthy
    
